fingerprintjs/fingerprintjs.com

src/css/_form-elements.scss, src/css/_forms.scss, src/js/index.js
- The Github star counter now shows the full number.
- The signup form borders now match the border width of the header buttons.
=> Show full star count and match signup form border width with buttons

content/blog/blog-test-page.md, gatsby-node.js, src/templates/blog.module.scss, src/templates/blog.tsx
Adds blog pagination.
Discussed with @Lisenish and we decided it's ok to branch from feature branches to keep tickets separate, so this depends on https://github.com/fingerprintjs/fingerprintjs.com/pull/54 being merged.
=> Blog pagination

src/components/Layout/index.tsx
=> removed mixpanel snippet

src/pages/demo/index.tsx, src/pages/pricing/index.tsx
=> added title tags for pricing and demo pages

src/components/common/Container/Container.module.scss, src/components/common/Container/index.tsx, src/templates/long-form-content.module.scss, src/templates/long-form-content.tsx
=> Changed size and spacing for blog layout.

src/components/UseCasesSection/UseCasesSection.module.scss, src/components/UseCasesSection/index.tsx
=> added learn more link on hover front page card

yarn.lock
=> chore: Update @fingerpringjs/fingerprintjs-pro

src/components/FpjsWidget/FpjsWidget.module.scss, src/components/demo/DemoSection/DemoSection.module.scss
Set max width for history column.
Fix demo section header alignment.
=> Set min width for widget.

src/components/FpjsWidget/FpjsWidget.module.scss
Closes WEB-93
Increased visitor ID font size to decrease distance with info icon
=> increased visitorId font size 

content/index/account-sharing.md, content/index/account-takeover.md, content/index/cryptocurrency.md, content/index/ecommerce.md, content/index/gaming.md, content/index/payment-fraud.md, content/index/why-fpjs.md, gatsby-node.js, package.json, src/components/Content/Content.module.scss, src/components/Content/Content.tsx, src/components/Post/Post.tsx, src/components/widgets/AlternatingImagesText/AlternatingImagesText.module.scss, src/components/widgets/AlternatingImagesText/index.tsx, src/components/widgets/CardGrid/CardGrid.module.scss, src/components/widgets/CardGrid/index.tsx, src/components/widgets/InlineCta/InlineCta.module.scss, src/components/widgets/InlineCta/index.tsx, src/components/widgets/SubHeader/index.tsx, src/helpers/format.tsx, src/styles/_mixins.scss, src/templates/long-form-content.tsx, src/templates/static-page-content.tsx, static/admin/config.yml, yarn.lock
Card content, image block text and CTA subtitle for the static page can now be edited as markdown.
Closes WEB-91
=> Added CMS markdown support.

src/components/ContactSalesForm/ContactSalesForm.module.scss, src/components/ContactSalesForm/index.tsx, src/pages/contact-sales/index.tsx
Makes the messages black so they show up on light backgrounds.
=> Added light variant for contact sales form.

package.json, yarn.lock
=> chore: Install experimental version of @fingerpringjs/fingerprintjs-pro

src/components/Header/Header.module.scss, src/components/Header/index.tsx, src/components/LiveDemoSection/LiveDemoSection.module.scss, src/components/Navbar/Navbar.module.scss
=>  fixed navigation bar on scroll

src/components/GetStartedForm/index.tsx, src/components/Header/index.tsx
https://fpjs.myjetbrains.com/youtrack/issue/WEB-123
Here are the changes to the homepage. Price slider options will be changed in the next PR (pricing page)
=> feature: free-tier Homepage changes

content/blog/why-it’s-not-just-netflix-losing-money-from-subscription-sharing.md, src/components/Content/Content.module.scss, static/admin/config.yml
of the article, I only changed the numbers of the list I don't know why github shows more changes
=> fix: nested bullet list bug

src/components/Footer/index.tsx, src/constants/content.ts
=> fix: added status page to footer

package.json, yarn.lock
Could you please deploy the changes today?
=> chore: Update @fingerpringjs/fingerprintjs-pro to v3.3.0-dev.7

src/components/githubPage/FeatureComparisonSection/FeatureComparisonSection.tsx, src/components/githubPage/GetStartedSection/GetStartedSection.tsx, src/components/githubPage/PricingSection/PricingSection.tsx
=> Feature: GitHub landing page updates for the free tier

src/components/Header/Header.module.scss, src/components/Header/index.tsx
=> fix: fixed signup button in mobile view

content/index/account-sharing.md, content/index/account-takeover.md, content/index/cryptocurrency.md, content/index/ecommerce.md, content/index/paywall.md, content/index/why-fpjs.md, src/components/common/Button/index.tsx, src/components/widgets/Hero/Hero.stories.tsx, src/components/widgets/Hero/index.tsx, src/templates/static-page-content.tsx, static/admin/config.yml
=> Feature: Add ability to open CTA link in a new tab

src/components/GetStartedForm/GetStartedForm.module.scss, src/components/GetStartedForm/index.tsx, src/components/Header/index.tsx, src/components/MobileNavbar/index.tsx, src/components/UseCasesSection/UseCasesSection.module.scss
=> Free trial copy update

src/components/Content/Content.module.scss
=> fix: added border radius to blog images

src/components/GetStartedForm/index.tsx, src/styles/vendors/tippy.scss
tooltip redesign requested in https://fpjs.myjetbrains.com/youtrack/issue/DASH-452
=> tooltip redesign

src/pages/pricing/index.tsx
=> added information about 500$ threshold on pricing page

content/index/ecommerce.md, content/index/gaming.md
Fix typos on e-commerce and gaming page.
=> fix(typos): fix typos on ecommerce and gaming pages

src/components/Layout/index.tsx
Closes WEB-158
For blog: `<meta property="og:type" content="blog">`
For rest of website: `<meta property="og:type" content="website">`
=> added og:type tags

src/components/HeaderBar/HeaderBar.module.scss, src/components/MobileNavbar/MobileNavbar.module.scss
=> fix:menu cannot be closed in mobile view

gatsby-config.js, package.json, src/templates/long-form-content.module.scss, src/templates/long-form-content.tsx, yarn.lock
=> Remove Disqus comments entirely

src/components/Header/index.tsx, src/components/MobileNavbar/index.tsx, src/constants/content.ts
Closes [WEB-300](https://fpjs.myjetbrains.com/youtrack/issue/WEB-300)
=> [Botd] Add botd link to header

src/components/botd/DocumentationSection/DocumentationSection.module.scss, src/components/botd/GenerateKeySection/GenerateKeySection.module.scss, src/components/botd/HeroSection/HeroSection.tsx, src/components/botd/IntegrationSection/IntegrationSection.tsx, src/components/botd/JoinCommunitySection/JoinCommunitySection.tsx, src/components/common/Button/Button.module.scss, src/components/common/CodeWindowWithSelector/CodeWindow.module.scss, src/components/common/Collapsible/Collapsible.module.scss, src/constants/content.ts, src/pages/botd/botd.module.scss
Mobile/tablet view fixes and changes requested by Kate and Dmitry:
- Change white buttons hover to opacity 70%
- Fix Github Link
- Add hover effect to Copy buttons
- Add documentation link
- Fix FAQ section animation
=> BotD: requested changes

src/templates/solution-content-template.tsx
Improve demo button label according to feedback from figma
=> Improve demo button label
